spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/todo
    username: todo
    password: todo
    driverClassName: org.postgresql.Driver

cors:
  allowed-origins: www.blackpantech.com

sql:
  init:
    platform: postgresql
